name: sparking:1.0.0
services:

  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django-2
    restart: always
    image: sparking:1.0.0
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONUNBUFFERED=1

  celery-worker:
    restart: unless-stopped
    container_name: celery-worker-2
    command: celery -A parking worker --loglevel=info
    image: sparking:1.0.0
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - django

  celery-beat:
    container_name: celery-beat-2
    command: celery -A parking beat --loglevel=info
    restart: unless-stopped
    image: sparking:1.0.0
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - django

  redis:
    image: redis:alpine
    container_name: redis-2
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:18
    container_name: db-postgres
    restart: always
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    ports:
      - "5432:5432"
