# Generated by Django 5.1.2 on 2026-02-17 09:47

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tariffType', models.CharField(max_length=100)),
                ('vehicleType', models.CharField(max_length=2)),
                ('priceHour', models.FloatField()),
                ('priceHourAdditional', models.FloatField()),
                ('maxPrice', models.FloatField()),
                ('segment', models.IntegerField()),
                ('startTime', models.IntegerField()),
                ('startTimeAdditional', models.IntegerField()),
                ('enableDays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]), blank=True, default=list, help_text='Días de la semana: 1=Lunes, 2=Martes, ..., 7=Domingo', size=None)),
            ],
        ),
    ]
