# Generated by Django 5.1.2 on 2026-02-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='startTime',
            new_name='startTimeCharge',
        ),
        migrations.AddField(
            model_name='tariff',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
