# Generated by Django 5.1.2 on 2026-02-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_rename_starttime_tariff_starttimecharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='tariffType',
            field=models.CharField(choices=[('1', 'Sencilla'), ('2', 'Por segmento')], default='1', max_length=2),
        ),
    ]
