# Generated by Django 5.1.2 on 2026-02-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_alter_tariff_tarifftype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='maxPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='priceHour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='priceHourAdditional',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariffType',
            field=models.CharField(choices=[('1', 'Sencilla'), ('2', 'Por segmento'), ('3', 'Apartir de n horas')], default='1', max_length=2),
        ),
    ]
