# Generated by Django 5.1.2 on 2026-02-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('fullName', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('imgURL', models.CharField(max_length=255, null=True)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
