# Generated by Django 5.1.2 on 2026-03-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0002_seed_municipios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='code_depto',
            new_name='deptoCode',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='code_municipio',
            new_name='municipioCode',
        ),
    ]
