# Generated by Django 5.1.2 on 2026-03-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0003_rename_code_depto_municipio_deptocode_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='municipio',
            name='idx_municipio_depto',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='depto',
            new_name='dpto',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='deptoCode',
            new_name='dptoCode',
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['dpto'], name='idx_municipio_depto'),
        ),
    ]
