# Generated by Django 5.1.2 on 2026-02-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='codeEI',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
