# Generated by Django 5.1.2 on 2026-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_alter_paymentmethod_codeei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='codeEI',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
