# Generated by Django 5.1.2 on 2025-10-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensualidades',
            fields=[
                ('placa', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('propietario', models.CharField(max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_venc', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('mora', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField()),
                ('cod_tarjeta', models.CharField(blank=True, max_length=45, null=True)),
                ('correo_e', models.CharField(blank=True, max_length=45, null=True)),
                ('placas_adicionales', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'mensualidades',
            },
        ),
    ]
