"""
Django settings for parking project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import environ
from pathlib import Path
from celery.schedules import crontab
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#*-------ENV--------
env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOST', default=['localhost'])
# ALLOWED_HOSTS = ['*']




#*----- USER -------
AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'celery',
    'corsheaders',
    'channels',
    'rest_framework',
    'rest_framework.authtoken',
    'apps.tariffs.apps.TariffsConfig',
    'apps.users.apps.UsersConfig',
    'apps.clientes.apps.ClientesConfig',
    'apps.mensualidades.apps.MensualidadesConfig',
    'apps.vip.apps.VipConfig',
    'apps.nequi.apps.NequiConfig',
    'apps.parking_info.apps.ParkingInfoConfig',
    'apps.movements.apps.MovementsConfig',
    'apps.sales.apps.SalesConfig',
    'apps.customers.apps.CustomersConfig',
    'apps.e_invoices.apps.EInvoicesConfig',
    'apps.payment_methods.apps.PaymentMethodsConfig',
    'apps.sales_reports.apps.SalesReportsConfig',
    'apps.taxes.apps.TaxesConfig',
    'apps.subscriptions.apps.SubscriptionsConfig',
    'apps.vehicles.apps.VehiclesConfig',
    'apps.municipios.apps.MunicipiosConfig',
    'apps.expenses.apps.ExpensesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'parking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

WSGI_APPLICATION = 'parking.wsgi.application'

ASGI_APPLICATION = 'parking.asgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWD'),
        'HOST': env('DB_IP'),
        'PORT': env('DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Bogota'
USE_TZ = False 

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#* ------- QUEUE --------
#*MESSAGE BROKER REDIS
CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

CELERY_BEAT_SCHEDULE = {
    # 'sync-movements': {
    #     'task': 'apps.movimientos.tasks.sync',
    #     'schedule': 30.0,  # Ejecutar cada 30 segundos
    # },
    # 'send-fe': {
    #     'task': 'apps.fe.tasks.send_to_dian',
    #     'schedule': crontab(minute='*/1'),  # Schedule the task to run every minute
    # },
    'clean-media-folder': {
        'task': 'apps.movements.tasks.clean_media_folder',
        'schedule': crontab(hour=0, minute=0),  # Schedule the task to run daily at midnight
    },
    'update-subscription-states': {
        'task': 'apps.subscriptions.tasks.update_subscription_states',
        'schedule': 60,  # Cada 5 minutos
    },
}

#* ------- MAIL --------
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = env('EMAIL_PORT')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = env('EMAIL_USE_TLS')

#*----- MEDIA FILES -----
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#*----- TGW -------
TGW_USER = env('TGW_USER')
TGW_PASSWD = env('TGW_PASSWD')

#*----- NEQUI -------
NEQUI_ACCESS_KEY = env('NEQUI_ACCESS_KEY')
NEQUI_SECRET_KEY = env('NEQUI_SECRET_KEY')
NEQUI_API_KEY = env('NEQUI_API_KEY')
NEQUI_ACTIVE = env.bool('NEQUI_ACTIVE', default=False)
NEQUI_SANDBOX = env.bool('NEQUI_SANDBOX', default=True)

#*----- Cors -------

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly'
    ],
}