# Generated by Django 5.1.2 on 2026-02-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('additionalInfo', models.TextField(blank=True, null=True)),
                ('includeLogo', models.BooleanField(default=True)),
                ('includeParkingInfo', models.BooleanField(default=True)),
                ('includeFeResolution', models.BooleanField(default=False)),
                ('includeQRCode', models.BooleanField(default=True)),
                ('ticketHeader', models.TextField(blank=True, null=True)),
                ('showQRCode', models.BooleanField(default=True)),
                ('includeBasicRules', models.BooleanField(default=True)),
                ('ticketFooter', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
