# Generated by Django 5.1.2 on 2026-02-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinginfo',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='nit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
