# Generated by Django 5.1.2 on 2026-02-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_info', '0002_alter_parkinginfo_address_alter_parkinginfo_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinginfo',
            name='showQRCode',
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parkinginfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
