# Generated by Django 5.1.2 on 2026-02-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_info', '0003_remove_parkinginfo_showqrcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinginfo',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
