# Generated by Django 5.1.2 on 2026-03-25 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0003_alter_paymentmethod_codeei_alter_paymentmethod_name'),
        ('sales_reports', '0001_initial'),
        ('subscriptions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amountPaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paymentMethodValue1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paymentMethodValue2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('paymentMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='payment_methods.paymentmethod')),
                ('paymentMethod1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments1', to='payment_methods.paymentmethod')),
                ('paymentMethod2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments2', to='payment_methods.paymentmethod')),
                ('saleReport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to='sales_reports.salesreport')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'db_table': 'subscription_payments',
            },
        ),
    ]
