# Generated by Django 5.1.2 on 2026-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_rebuild_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='endDate',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='startDate',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
