# Generated by Django 5.1.2 on 2026-02-26 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tariffs', '0002_rename_starttime_tariff_starttimecharge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('nTicket', models.BigAutoField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=15)),
                ('entryTime', models.DateTimeField(auto_now_add=True)),
                ('exitTime', models.DateTimeField(null=True)),
                ('vehicleType', models.CharField(max_length=6)),
                ('card', models.CharField(max_length=20, null=True)),
                ('speciality', models.CharField(blank=True, default='NORMAL', max_length=20, null=True)),
                ('parkingTime', models.CharField(max_length=50)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariffs.tariff')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movement',
                'verbose_name_plural': 'Movements',
                'db_table': 'movements',
                'indexes': [models.Index(fields=['exitTime'], name='idx_exit_time'), models.Index(condition=models.Q(('exitTime__isnull', True)), fields=['plate'], name='idx_plate_active')],
            },
        ),
    ]
