# Generated by Django 5.1.2 on 2026-02-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='parkingTime',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
