# Generated by Django 5.1.2 on 2025-09-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NequiTxn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recibo', models.PositiveIntegerField()),
                ('init_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('user', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=50)),
                ('code_qr', models.CharField(default='', max_length=60)),
                ('msg_desc', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'nequi_txn',
            },
        ),
    ]
