# Generated by Django 5.1.2 on 2025-10-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nequi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nequitxn',
            name='code_qr',
            field=models.CharField(default='', max_length=100),
        ),
    ]
