# Generated by Django 5.1.2 on 2025-10-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
                ('tipo_persona', models.CharField(max_length=12)),
                ('tipo_doc', models.CharField(max_length=45)),
                ('n_doc', models.CharField(max_length=45)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('cod_postal', models.CharField(blank=True, max_length=45, null=True)),
                ('depto', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_depto', models.CharField(blank=True, max_length=20, null=True)),
                ('municipio', models.CharField(blank=True, max_length=80, null=True)),
                ('cod_municipio', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('tributo', models.CharField(max_length=60)),
                ('responsabilidades', models.CharField(max_length=45)),
                ('placa', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
