# Generated by Django 5.1.2 on 2026-02-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(max_length=50)),
                ('issueDate', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=50)),
                ('track_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('errors', models.TextField(blank=True, null=True)),
                ('saleID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e_invoices', to='sales.sale')),
            ],
            options={
                'verbose_name': 'EInvoice',
                'verbose_name_plural': 'EInvoices',
                'db_table': 'e_invoices',
            },
        ),
    ]
