# Generated by Django 5.1.2 on 2026-03-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='codeEI',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
