# Generated by Django 5.1.2 on 2026-02-27 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('movements', '0002_alter_movement_parkingtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codeFe', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'PaymentMethod',
                'verbose_name_plural': 'PaymentMethods',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxPercent', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxValue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.CharField(max_length=255, null=True)),
                ('additionalNote', models.CharField(max_length=255, null=True)),
                ('paymentMethodValue1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paymentMethodValue2', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('customerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='movements.movement')),
                ('paymentMethod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.paymentmethod')),
                ('paymentMethod1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales1', to='sales.paymentmethod')),
                ('paymentMethod2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales2', to='sales.paymentmethod')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'db_table': 'sales',
            },
        ),
    ]
