# Generated by Django 5.1.2 on 2026-02-27 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='paymentMethod1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales1', to='payment_methods.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='paymentMethod2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales2', to='payment_methods.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='paymentMethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='payment_methods.paymentmethod'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
