# Generated by Django 5.1.2 on 2026-03-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_paymentmethod1_alter_sale_paymentmethod2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amountPaid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
