# Generated by Django 5.1.2 on 2026-03-08 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_amountpaid'),
        ('sales_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='saleReport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales_reports.salesreport'),
        ),
    ]
