# Generated by Django 5.1.2 on 2026-03-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_salereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='taxPercent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
