# Generated by Django 5.1.2 on 2025-08-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=15, unique=True)),
                ("propietario", models.CharField(max_length=45)),
                ("vigencia", models.DateField()),
                ("activo", models.IntegerField()),
                ("amparadas", models.CharField(blank=True, max_length=35, null=True)),
                ("tarjeta", models.CharField(blank=True, max_length=100, null=True)),
                ("rol", models.CharField(blank=True, max_length=45, null=True)),
                ("nota", models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                "db_table": "vip",
            },
        ),
    ]
