# Generated by Django 5.1.2 on 2026-03-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_brand_vehicle_color'),
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='vigencia',
            new_name='caducate',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='tarjeta',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='activo',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='nota',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='amparadas',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='placa',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='vip',
            name='rol',
        ),
        migrations.AddField(
            model_name='vip',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vips', to='vehicles.vehicle'),
            preserve_default=False,
        ),
    ]
