# Generated by Django 5.1.2 on 2026-03-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_vip_update_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vip',
            options={'verbose_name': 'VIP', 'verbose_name_plural': 'VIPs'},
        ),
    ]
